name: Linux

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-18.04
    compiler: gcc
    gcc: 10
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8.10'
        architecture: 'x64'
    - name: Apt Update
      run: sudo apt-get update
    - name: Configure
      run: ./configure --openssl-no-asm --without-intl
    - name: Compile
      run: make -j2
    - name: Get kmake_bin
      run: git clone https://github.com/Kode/kmake_bin.git
