name: Windows

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Compile
      run: .\vcbuild.bat openssl-no-asm without-intl
      continue-on-error: true
    - name: Compile some more
      run: .\vcbuild.bat openssl-no-asm without-intl
    - name: Get kmake_bin
      run: git clone https://github.com/Kode/kmake_bin.git
    - name: Copy binary
      run: copy Release\node.exe kmake_bin\kmake.exe
    - name: Set name
      run: git config --global user.name "Robbot"
    - name: Set email
      run: git config --global user.email "robbot2019@robdangero.us"
    - name: Commit binary
      run: git -C kmake_bin commit -a -m "Update Windows binary to ${env:GITHUB_SHA}."
    - name: Push binary
      run: git -C kmake_bin push https://Kode-Robbot:${env:ROBBOT_PASS}@github.com/Kode/kmake_bin.git master --tags
      env:
        ROBBOT_PASS: ${{ secrets.ROBBOT_PASS }}
